### ISSUE TITLE
E471: Argument required

### ISSUE THREAD

**Issue by ubaldot** [jpalardy/vim-slime#324] opened 2022-04-05 17:17 UTC
I am running `Vim 8.2` on `Windows 10`. 
The command `:SlimeSendCurrentLine` works well, but the `:SlimeSend`,  `:SlimeSend0` and  `:SlimeSend1` give me the` error E471: Argument required.` 

The only things related to vim-slime on my `.vimrc` are the following:

```
let g:slime_python_ipython = 1
let g:slime_target = "vimterminal"
let g:slime_cell_delimiter = "# %%"
```
Any hint on how to fix the problem?

**Comment by jpalardy** [comment] 2022-04-05 22:37
Hi @Barzi2001 

Do you know what line/function is causing a problem?

If you give me a step-by-step, I can try to reproduce (minx the windows 10 part)

**Comment by Barzi2001** [comment] 2022-04-06 08:30
Actually all give me problems.
You can try for example this:

```
# %%
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

A = 3
B = 4
C = A + B

# %%

```

**Comment by jpalardy** [comment] 2022-04-07 04:54
Hi @Barzi2001 

what I did:
* new docker container, ubuntu:latest image
* put (only) your config in .vimrc
* install vim, ipython3, vim-slime
* start vim, `:terminal`, `ipython3`

![Screen Shot 2022-04-06 at 21 50 02](https://user-images.githubusercontent.com/18142/162122552-f4be7a0b-9687-4a6f-92fb-8e4fc15a9370.png)

* sent text with `ctrl-c` `ctrl-c`
* picked existing terminal (no 1)

…

I skipped the imports, not sure it was relevant to this problem

**Comment by jpalardy** [comment] 2022-04-07 04:57
```
# ipython3 --version
7.13.0
```
🤔

**Comment by jpalardy** [comment] 2022-04-08 02:34
This certainly looks like it's breaking on the vim-slime side (rather than anything having to do with Windows and/or ipython)

`:help e471` says

```
                                                        E471
  Argument required

This happens when an Ex command with mandatory argument(s) was executed, but
no argument has been specified.
```

which isn't exactly enlightening… 😐 

If you want to sprinkle the plugin code with [echom](https://learnvimscriptthehardway.stevelosh.com/chapters/01.html) and let me know what you find, I can try to help.

**Comment by Barzi2001** [comment] 2022-04-08 15:31
I am not sure I can use this feature, but I run` :echom` followed by `:SlimeSend0` obtaining the same `e471` error again with no more info (I also checked in `:messages`).
I also tried to uninstall/reinstall the plugin but it didn't help. 

**Unrelated:** every time I try to use vim-slime I have to run `:SlimeConfig` manual and select the target window of my slimes. 
I am aware that in specify a default terminal in my `.vimrc`, but what shall I write if I have a cryptical message like this? What is the terminal name and the session name?! 

![image](https://user-images.githubusercontent.com/10845685/162474224-e47e84b8-0943-49c8-aa11-f24fd11d6ef5.png)

**Comment by jpalardy** [comment] 2022-04-09 02:08
Hi @Barzi2001 

I use tmux because I can default to 

```vim
let g:slime_target = "tmux"
let g:slime_default_config = {"socket_name": "default", "target_pane": "{last}"}
let g:slime_dont_ask_default = 1
```

and `{last}` "just works"…

if there's a vimscript way to inspect and (intelligently) pick the vim-terminal … it's not part of the plugin 😩

**Comment by Barzi2001** [comment] 2022-04-11 09:43
**UPDATE:** If I run e.g. `:SlimeSend0 1000`, then `1000 ` is "slimed" to the `REPL`. 
I am not sure, but it seems the argument to be passed to `:SlimeSend0` is what is in between the delimiters (`# %%` in my case) and it seems that the command `:SlimeSend0` simply fails at picking it?

**Comment by jpalardy** [comment] 2022-04-13 02:11
`:SlimeSend0` and `:SlimeSend1` are not overly publicized. They take strings as argument and directly send those over (no relation to buffer content or selection)

**Closed** 2023-01-07 19:54 UTC
Labels: wontfix
