### ISSUE TITLE
Ipython 5.0.0 in tmux  - Have to send lines twice

### ISSUE THREAD

**Issue by nigeljyng** [jpalardy/vim-slime#109] opened 2016-07-11 09:09 UTC
I'm using Vim-slim with IPython 5 in tmux. Before this, I can send blocks of text by highlighting text in visual mode, then doing the Ctrl-C, Ctrl-C command. But since the upgrade to IPython 5, Ctrl-C, Ctrl-C only seems to enter pasting mode, without actually pasting the text. I have to do the Ctrl-C sequence twice for the text to paste.

Here's a few screenshots to show what I mean:

### Start:
![1](https://cloud.githubusercontent.com/assets/13656877/16725335/ab0ba026-474e-11e6-9660-e88cce418855.png)

### If I send a single line, things work as usual:
![screen shot 2016-07-11 at 10 04 06](https://cloud.githubusercontent.com/assets/13656877/16725371/dc8baa42-474e-11e6-85cd-df4dfa4d54fc.png)

### But if I highlight a few lines and hit send, it seems to just enter %cpaste mode, without sending anything:
![screen shot 2016-07-11 at 10 04 52](https://cloud.githubusercontent.com/assets/13656877/16725399/f61aa698-474e-11e6-854d-04de207520b3.png)

### I have to hit Ctrl-C, Ctrl-C again to send lines:
![screen shot 2016-07-11 at 10 05 55](https://cloud.githubusercontent.com/assets/13656877/16725423/17560b68-474f-11e6-9fd1-4e6de1574a53.png)

Any chance this can get a fix?

**Comment by jpalardy** [comment] 2016-07-14 00:41
Hi there,

Just to be clear: are you saying everything worked in iPython < 5 and now it doesn't?

**Comment by nigeljyng** [comment] 2016-07-14 08:42
Yes. Everything worked on IPython 4.x. I only encountered this problem after upgrading to IPython 5.

**Comment by vrivellino** [comment] 2016-07-15 15:05
@jpalardy (cc @nigeljyng): I submitted a small PR to fix this issue. It looks like sending `%cpaste` separately from the code to IPython fixes this issue.

**Comment by jpalardy** [comment] 2016-07-15 16:07
merged: thanks to @vrivellino .

Let me know if it's still a problem.

**Comment by rsmith31415** [comment] 2016-07-15 20:40
@jpalardy Are you sure this fixes the issue? I updated with Vundle and verified that the latest PR was included, but I still see the same behavior. 

Using neovim 0.1.5-dev, tmux 2.1, Ubuntu 16.04

**Comment by jpalardy** [comment] 2016-07-15 21:33
@vrivellino thoughts?

**Comment by vrivellino** [comment] 2016-07-16 13:31
@jpalardy I actually use screen locally and didn't think twice that the fix may not work for tmux. I'll install tmux locally and see if I can reproduce.

At the end of the day, something changed on the IPython side and, ultimately, an issue might need to raised there.

For example, I just started up ipython in a terminal (not in tmux or screen), copied the following text in my keyboard ...
```
%cpaste
print 'hello'
print 'world'
--
```

... and pasted into the ipython terminal:

![image](https://cloud.githubusercontent.com/assets/1489368/16895078/db2ebe0e-4b37-11e6-88cf-d081e540bad3.png)

So the `%cpaste` magic input handling is behaving differently than in IPython 4.

**Comment by vrivellino** [comment] 2016-07-16 13:41
@jpalardy @rsmith31415: I just installed tmux locally and I couldn't reproduce - vim-slime was behaving as expected.

However, I'm on a Mac running El Capitan with vim 7.4 and tmux 2.2 installed via homebrew. Perhaps my workaround doesn't work on Linux?

**Comment by rsmith31415** [comment] 2016-07-16 22:29
@vrivellino I believe this can be an issue on Linux. I was able to reproduce this bug in a fresh installation (EC2) with tmux 2.1 (and 2.2) and vim 7.4.

![screenshot from 2016-07-16 17-19-03](https://cloud.githubusercontent.com/assets/599274/16897569/d55d06d2-4b7a-11e6-8376-7972b5d5e31d.png)

**Comment by nigeljyng** [comment] 2016-07-18 08:49
@vrivellino @jpalardy I can confirm the PR fixed the issue for me. Using Ipython 5.0.0, OSX El Capitan, tmux in iTerm2

**Comment by jpalardy** [comment] 2016-07-18 16:15
ok, thanks ^

**Comment by rsmith31415** [comment] 2016-07-18 20:05
@jpalardy Should I open another issue for Linux?

**Comment by jpalardy** [comment] 2016-07-18 20:25
We're all here, let's keep this issue for now.

**Comment by vrivellino** [comment] 2016-07-18 21:32
FWIW - I just spun up an EC2 instance running Amazon Linux with vim 7.4, tmux 1.8, IPython 5.0.0 works OK.

I'm going to try install neovim real quick to see if that's the issue. May give Ubuntu a go if I get some time.

**Comment by vrivellino** [comment] 2016-07-18 21:51
@rsmith31415: Can you doublecheck your vim config? I just installed nvim and reproduced your error, but it was because I hadn't imported my vim config ... specifically `let g:slime_python_ipython = 1`.

For example, with slime_python_ipython not set:

![image](https://cloud.githubusercontent.com/assets/1489368/16931439/0972cbec-4d0f-11e6-9aa5-023549d78d33.png)

Above is after I interrogated `g:slime_python_ipython` to show it's not set.

After I re-enable `let g:slime_python_ipython=1` in my config it seems to work fine, with one catch:
![image](https://cloud.githubusercontent.com/assets/1489368/16931652/0c4face4-4d10-11e6-8716-f02f6fd3dd9d.png)

The very first time text is sent over to tmux/IPython it's not echo'd in my terminal. However, after that everything is. (However, you can see that it worked.)

**Comment by rsmith31415** [comment] 2016-07-18 21:53
@vrivellino I think that is very likely to be the issue here. I didn't receive the red box you show in the first image though. Interestingly, it used to work in IPython 4, but I will check after including `let g:slime_python_ipython = 1` in my configuration file.

**Comment by vrivellino** [comment] 2016-07-18 21:59
@rsmith31415 The red box was generated by me entering `:let g:slime_python_ipython` in command mode. I'm pretty certain it needs to be enabled. Also, by enabling it IPython won't attempt auto-indent text that pasted in via vim-slime, so IMO it's a good idea to enable.

@jpalardy: You may want to highlight something in the readme that IPython 5 users may need to have slime_python_ipython enabled.

**Comment by jpalardy** [comment] 2016-07-18 22:03
From reading the code again, isn't `let g:slime_python_ipython = 1` [always needed](https://github.com/jpalardy/vim-slime/blob/master/ftplugin/python/slime.vim#L3) for iPython? Is there something different about v5 I'm not getting?

**Comment by rsmith31415** [comment] 2016-07-18 22:10
@vrivellino  Yes, that definitely works but I was making another mistake. Previously, I was able to send commands to IPython without saving the file. Now, you need to save the file and then it will receive the whole input.

By the way, regarding `let g:slime_python_ipython`, I didn't use it previously and still worked (with IPython 4), but I don't think it is a problem if that is required.

I noticed a small detail. When you send some code, there is an uneven indentation inside the %cpaste block between the first line and the second line:

```
In [11]: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:import logging
import sys
import os
--
:::

```

Why is that?

**Comment by vrivellino** [comment] 2016-07-18 22:20
@jpalardy Yes it is. When I mentioned updating the [IPython readme](https://github.com/jpalardy/vim-slime/blob/master/ftplugin/python/README.md), I should have said "IPython 5 users **must** have `let g:slime_python_ipython = 1`." :)

@rsmith31415 
> Previously, I was able to send commands to IPython without saving the file. Now, you need to save the file and then it will receive the whole input.

Hmm ... I've never experienced that.

> I noticed a small detail. When you send some code, there is an uneven indentation inside the %cpaste block between the first line and the second line:

That's a by-product of how IPython is handling pasted input with `%cpaste`, and I don't think there's a simple way around this.  To illustrate this, fire up IPython (doesn't have to be tmux or screen), then enter `%cpaste`:

![image](https://cloud.githubusercontent.com/assets/1489368/16932359/de311e5c-4d13-11e6-9501-792bb1abc7c1.png)

Copy the following text to your clipboard:
```
print 'hello'
print 'world'
--
```

And paste it into IPython:
![image](https://cloud.githubusercontent.com/assets/1489368/16932372/f7f73ac4-4d13-11e6-9647-b95e42d1c3b3.png)

That's the behavior you're seeing.

Now, if you were to enter those lines one-by-one (not copied and pasted):
![image](https://cloud.githubusercontent.com/assets/1489368/16932397/1aa74c80-4d14-11e6-9790-4ad15fae033e.png)

IPython is printing `:` for each line of the `%cpaste` prompt. I'd say they should just remove that prompt, there's no need for it you're pasting in code.

**Comment by rsmith31415** [comment] 2016-07-18 22:36
@vrivellino  You're absolutely right. It is a bit annoying, but not a big deal. Thank you for the help.

**Comment by jpalardy** [comment] 2016-07-19 03:46
I added [a note about IPython 5](https://github.com/jpalardy/vim-slime/commit/2a94dace112c5a7c51d2456f0d7fb2bf51630030).

Good? Or does it need better wording?

**Comment by vrivellino** [comment] 2016-07-19 12:17
@jpalardy 👍 Looks OK to me

**Comment by jpalardy** [comment] 2016-07-19 15:42
excellent

**Closed by jpalardy** 2016-07-19 15:42 UTC
