### ISSUE TITLE
neovim terminal doesn't appear to work for me

### ISSUE THREAD

**Issue by sanga** [jpalardy/vim-slime#232] opened 2020-03-28 10:52 UTC
I get the following error

```
Error detected while processing function slime#send_op[19]..slime#send[13]..<SNR>204_SlimeDispatch[2]..<SNR>204_NeovimSend:
line    5:
E716: Key not present in Dictionary: jobid
E116: Invalid arguments for function str2nr
E116: Invalid arguments for function chansend
```

This is against version:

```
NVIM v0.5.0-418-g87d892afa
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-c48d5551-5074-4a05-b117-d6e98b5fddaa

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
```

After having set `let g:slime_target="neovim"` and then hitting `ctrl C C`

**Comment by sanga** [comment] 2020-03-28 11:03
This might be a timing thing actually. I dropped a small sleep into vim-slime and I'm not getting that error anymore

**Comment by jpalardy** [comment] 2020-03-29 19:47
@a-vrma @MaxSt thoughts?

**Comment by a-vrma** [comment] 2020-03-30 21:54
I can't reproduce it on Neovim v0.4.3. I can download the 0.5 alpha and take a look at it soon.

**Comment by sanga** [comment] 2020-03-31 05:59
`0.4.3` still fails for me but in a slightly different manner i.e.

```
Error detected while processing function slime#send_op[19]..slime#send[13]..<SNR>212_SlimeDispatch[2]..<SNR>212_NeovimSend:
line    5:
Can't send raw data to rpc channel
```

**Comment by MaxSt** [comment] 2020-03-31 09:02
> `0.4.3` still fails for me but in a slightly different manner i.e.
> 
> ```
> Error detected while processing function slime#send_op[19]..slime#send[13]..<SNR>212_SlimeDispatch[2]..<SNR>212_NeovimSend:
> line    5:
> Can't send raw data to rpc channel
> ```

Are you sure you have set the correct job_id for the terminal?

https://github.com/jpalardy/vim-slime/blob/a0296a66ca29665707ed0fc942a846f68b337663/doc/vim-slime.txt#L141-L142

**Comment by sktrinh12** [comment] 2020-05-31 03:44
is it cool I revive this issue? I have the same problem. I tried entering `echo b:terminal_job_id `in `:te`. I don't get anything. I get `Error detected while processing function slime#send_op[19]..slime#s
end[13]..<SNR>132_SlimeDispatch[6]..<SNR>132_NeovimSend:
line    5:
E900: Invalid channel id`
when I try the <C-c><C-c> command. I typed `:SlimeConfig` and brought up the job id prompt, but I don't know what to enter. Btw, I put neovim in a docker image, making it a little more complex to troubleshoot. Is it even possible to have a docker image of neovim with `vim-ipython-cell` and `vim-slime`? I made a github repo of the dockerfile: [https://github.com/sktrinh12/neovim_docker](nvim_docker)

**Comment by jpalardy** [comment] 2020-05-31 19:11
Hi @sktrinh12,

Yes, I'm OK with this.

However, I don't have specific insights into the neovim terminal plugin (I use tmux, day to day). Two thoughts:

- if you're willing to investigate, I can help
- if you can loop in the neovim contributors (`git blame`), even better :-)

let me know

**Comment by sktrinh12** [comment] 2020-06-07 20:11
hi @jpalardy, i tried a few more things and realized i wasn't using the terminal correctly. I finally got the `terminal_job_id` to output by actually moving to the terminal pane and entering that command, I was entering it from the editor (－‸ლ). After having set the proper `jobID` and moving back to the editor to try `C-c` on a set of code `for i in range(10); print(i)`, I no longer get that error message, however in the terminal I get, `syntax error: Unexpected word (expecting ")")`. I think because it is not a python REPL that is interpreting it? The terminal is showing the current working directory like a bash prompt. Is it simply setting the config to the python interpreter? I'm not sure how to do this and I couldn't find anything pertinent on the github page. I already set the following in  the `init.vim` file: 
```
let g:slime_target = "neovim"
let g:slime_dont_ask_default = 1
let g:slime_cell_delimiter = "#%%"
nmap <leader>s <Plug>SlimeSendCell
```

**Comment by a-vrma** [comment] 2020-06-07 20:16
@sktrinh12 you are supposed to run a (i)python repl in the terminal buffer manually

**Comment by sktrinh12** [comment] 2020-06-07 20:22
@a-vrma thanks so much, didn't realise that! complete newb! one last question, how to point it to a different python version? it is using 2.7, but I have 3.7 installed.

**Comment by sktrinh12** [comment] 2020-06-07 21:28
Is there a way to pipe the `echo b:terminal_job_id` to bash and save the `jobid` so that on startup I don't have to manually type it? Can I then use the override function from the Github page to set the jobid value from an environmental variable? what's the best way to handle this? I put the following in my `init.vim` file. And also placed `autocmd VimEnter * SlimeOverrideConfig` underneath; but on startup I get a no command found error. Not sure if I understand the override config thing correctly.

```
function SlimeOverrideConfig()
  let b:slime_config = {}
  let b:slime_config["jobid"] = input("jobid: ", "default jobid value")
endfunction
```

**Closed** 2020-08-14 03:00 UTC
Labels: wontfix

**Comment by Afonsocraposo** [comment] 2020-09-15 17:00
I used the function by @sktrinh12 and made an automatic way to set the correct jobid:
```
let g:slime_target = "neovim"
let g:slime_dont_ask_default = 1
let g:slime_cell_delimiter = "###

autocmd Filetype python nnoremap <leader>S :call StartIPython<CR>

function SlimeOverrideConfig()
  let l:job_id = trim(execute(":echo b:terminal_job_id"))
  let b:slime_config = {}
  let b:slime_config["jobid"] = job_id
endfunction

function StartIPython()
    :vsplit
    :terminal
    :call SlimeOverrideConfig()
    :SlimeSend1 ipython --matplotlib
    :vertical resize 70
    :wincmd h
endfunction
```
I hope it can help somebody :)
